# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b80a640faa6fbc363d6cbe07c927b9a1332f0f7d31ea8e25af625d74288aea750ccf7b69ef75fdbd638623bd4bb5a41b8d3b3e20f33788416c4c81e320b66e94

test:
  secret_key_base: 04b8face8cd1459836b70cfe3dc4ddced587a124a8d6f1daca2be242c30000ad7b7fa36d232f68ad05a9b686c4d1ae7402d7f59ff4de2ff359abd841140054ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
